### PR TITLE
Appveyor CI and X64

### PR DESCRIPTION
**Pull request by chcg**
- added appveyor.yml CI config, see corresponding CI build at https://ci.appveyor.com/project/chcg/npptoolbucket/build/1.7.3
- added x64 config + necessary updates to
-- dllexport, PluginCore/NppPluginNETHelper.cs from https://github.com/kbilsted/NotepadPlusPlusPluginPack.Net
-- dotnetframework 4, needed to link properly
-- FindAndReplace.cs name collision with system.action

### CODE REVIEW

**Comment by phdesign** [comment]
This looks great, thank you. I'll pull it down and ensure it builds correctly for me before merging.

**Comment by phdesign** [comment]
Getting error "This ANSI plugin is not compatible with your Unicode Notepad++",from this [StackOverflow article](https://stackoverflow.com/questions/41752785/how-to-switch-dll-creation-from-ansi-into-unicode-in-visual-studio-2015) I think it's my VS setup rather than the solution.

**Comment by phdesign** [comment]
Confirmed this works in VS2015 but not VS2017, have a send a [pull request](https://github.com/chcg/NppToolBucket/pull/1) to fix it, can you confirm this still works in VS2015? 

Also, I don't get any icons in toolbar of the x64 version, you?

**Comment by chcg** [comment]
@phdesign Could confirm the issue for VS2017 with ANSI, because lib.exe is now with vs2017 at e.g. "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\bin\HostX64\x64\lib.exe".

Maybe setting VCToolsInstallDir=c:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\ could be used to construct the path.

Therefore the lib is not correctly build and the ansi issue, because isunicode doesn't answer correctly. Unfortunately there is no error message about this missing tool.

It is also ok to remove the path for VS2015. I will update the PR and add a VS2017 appveyor config.

**Comment by chcg** [comment]
@phdesign Updated plugin list for PluginManager with version v1.8 for x86 and also for x64, see https://github.com/bruderstein/npp-plugins-x64/commit/ad922f1542ef4743dd19bed3eeaa4f392283ac49

**Pull request merged**
